### ISSUE TITLE
tslint problem

### ISSUE THREAD

**Issue by kimbichi** [wagerfield/nuxt-typescript#7]
tslint souldn't check typescripts that is in the node_modules folder

**Comment by wagerfield** [comment]
This is something that you must configure in `tsconfig.json` using the `include/exclude` arrays of globbing patterns:

http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

When using TypeScript with Nuxt, I have found it's easier to nest all your project source files in a folder like `src` rather than having them at the root of your repo. This makes it much easier to specify the globbing patterns to `include` only your source files.

If you want to take this approach, move all your Nuxt source files into a directory like `src` eg.

```
src
- pages
  - index.vue
- store
  - index.ts
nuxt.config.js
```

...and then in your `nuxt.config.js` file (which should remain at the root of your repo) add the [`srcDir` property](https://nuxtjs.org/api/configuration-srcdir) and specify the name of the folder containing your Nuxt source files eg.

```js
// nuxt.config.js
module.exports = {
  srcDir: 'src'
}
```

Then in your `tsconfig.json` (which should be at the root of your repo) you can specify the files to include and TSLint will pick this up too:

```json
{
  "compilerOptions": {
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.vue"
  ]
}
```

Alternatively, if you don't want to do this, you can ignore the `node_modules` dir using an undocumented property in your `tslint.json` file:

```json
{
  "defaultSeverity": "warning",
  "extends": [
    "tslint:latest",
    "tslint-config-prettier"
  ],
  "linterOptions": {
    "exclude": [
      "node_modules"
    ]
  }
}
```
